services:
  pflegeplanung:
    build: .
    container_name: pflegeplanung
    restart: unless-stopped

    volumes:
      # Datenbank persistent speichern
      - ./instance:/app/instance

    environment:
      - FLASK_ENV=production
      - SECRET_KEY=aendere-mich-auf-einen-langen-zufalls-string

    ports:
      - "9500:5000"
